name: devfest_dart_code_lab
version: 0.1.0
author: Jana Moudra <jana.moudra@gmail.com>
description: Dart server side code lab for DevFest Istanbul 2015.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  rpc: ^0.5.5
  http: '>=0.11.1 <0.12.0'
  crypto: '>=0.9.0 <0.10.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
